name: multiprinter
description: A comprehensive example demonstrating all features of the multiprinter package.

publish_to: "none"

project_name: multiprinter
version: 1.0.0+0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  shared_preferences: ^2.3.0
  multiprinter_package:
    path: ../
  provider: ^6.1.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
